# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: git clone https://github.com/synthetichealth/synthea.git
  displayName: 'clone synthea'

- script: |
    cd synthea
    ./run_synthea -p 2
  displayName: 'run synthea'
